language: python
dist: xenial
python:
  - 3.6
  - 3.7
cache: pip
before_install:
#  - chmod +x travis_test.sh
#  - chmod +x travis_success.sh
  - pip install codecov
  - pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 wxPython
install:
  - pip install -r requirements.txt
script:
#  - pytest
  - coverage pytest
after_success:
  - codecov --token=$CODECOV_TOKEN